name: new version

on:
  schedule:
  - cron:  '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: checkout tag
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.previoustag.outputs.tag }}
    - name: 'Get next patch version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - name: New Version
      run: echo ${{ steps.semvers.outputs.patch }}